# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1: 
    root: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  showConsole: true
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
    sidebar:
      fontSize: 12px
      borderRadius: 10px
      activeTextColor: blue
    typography:
      fontSize: 17px
      heading1:
        color: '#250ce8'
        lineHeight: 0em
      heading2:
        lineHeight: 2.5em
      heading3:
        lineHeight: 2.5em
      heading4:
        lineHeight: 2.5em
  
  onlyRequiredInSamples: true

  expandResponses: '200'

  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python

